### ISSUE TITLE
HRK Doesn't save

### ISSUE THREAD

**Issue by JustSxm** [CortexPE/Hierarchy#11]
Is it because it isn't added yet?

Roles given aren't saved on Server restart

**Comment by JustSxm** [comment]
forgot to say Im using yaml

**Comment by CortexPE** [comment]
Steps to reproduce?

Member data is synchronously saved individually to their own filenames right after they are processed... There should be no interferences with it regarding server restart.

**Comment by JustSxm** [comment]
Set Database in config to yaml, Create some roles, set them to a player and close the server.Reoppen the server. The roles you created will be saved, but the members are back to the default role

**Comment by CortexPE** [comment]
Debugged & reproduced

**Comment by CortexPE** [comment]
Pushing patch later
