### ISSUE TITLE
1.12 Perms Broken

### ISSUE THREAD

**Issue by JustSxm** [CortexPE/Hierarchy#12]
In 1.12 basic commands such as /me and /kill permissions can not be removed

**Comment by CortexPE** [comment]
Steps to reproduce?

**Comment by JustSxm** [comment]
Remove Members Permission the me command , save and start the server. Members group can still do /me

**Comment by CortexPE** [comment]
Send configuration files?

You can remove permissions by prefixing it with a dash (-) character

**Comment by CortexPE** [comment]
stale
