### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by sobbingsmcpe** [CortexPE/Hierarchy#17]
So whenever i try to run the plugin, im getting an error for [21:28:38] [Server thread/CRITICAL]: Error: "Call to a member function getVirionClassLoader() on null" (EXCEPTION) in "plugins/Hierarchy-master/src/poggit/libasynql/base/SqlSlaveThread" at line 56, any situations or requirements i need to install on the server for the Hierarchy plugin to work?

**Comment by Thunder33345** [comment]
You might have to install this via the download links provided

**Comment by CortexPE** [comment]
download it from [here](https://poggit.pmmp.io/ci/CortexPE/Hierarchy/~)
