### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Arcoz0308** [CortexPE/Hierarchy#34]
19:02:13] [Server thread/CRITICAL]: Error: "Class 'poggit\libasynql\libasynql' not found" (EXCEPTION) in "plugins/Hierarchy-master/src/CortexPE/Hierarchy/data/member/SQLMemberDS" at line 51

**Comment by CortexPE** [comment]
Download from poggit: https://poggit.pmmp.io/ci/CortexPE/Hierarchy/~
