### ISSUE TITLE
could add MySQL option of permission per server!

### ISSUE THREAD

**Issue by ppaalo** [CortexPE/Hierarchy#37]
example: I have a Factions and SkyBlock server, in skyblock the vip has a fly, in Factions the vip does not have a fly

**Comment by artulloss** [comment]
Or instead you could change the permission for the faction server to faction.fly and change the permission for skyblock to skyblock.fly.

**Comment by CortexPE** [comment]
The right way to do this is with roles

Roles can have different permissions per server.

Simply set the permission to a VIP role on skyblock but not on factions...
Just make sure the role ID is the same across servers
