### ISSUE TITLE
Multi-Language support

### ISSUE THREAD

**Issue by justin-eckenweber** [CortexPE/Hierarchy#8]
Hey,

I really like the project Hierarchy. Finally a better plugin than PurePerms. It would be nice to have multi-language support so, if you want I can translate hierarchy into german just contact me via discord: Schdow#6718 I've already translated "MCPE Server Maker" it was an app to create mcpe servers via your mobile well... it's down now but nvm.

**Comment by CortexPE** [comment]
The `messages.yml` file is provided for this specific purpose... You can add translations there then we can add it to the repo so that everyone can use it.

**Comment by justin-eckenweber** [comment]
Ahh, i see. thank you

**Comment by Thunder33345** [comment]
where's the messages.yml?
is it not generated?
would be nice to generate it for translators
